/* eslint-disable react-hooks/exhaustive-deps */
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { getServerSideToken } from '@/utils/getServerSideToken';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export const getServerSideProps = getServerSideToken;

export default function Home() {
  const [currentImage, setCurrentImage] = useState<string>('');

  const images = [
    '/images/notebook1.jpg',
    '/images/notebook2.jpg',
    '/images/notebook3.jpg',
    '/images/notebook4.jpg',
  ];

  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentImage((prevImage) => {
        const currentIndex = images.indexOf(prevImage);
        const nextIndex = (currentIndex + 1) % images.length;
        return images[nextIndex];
      });
    }, 3000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.wrapper}>
        <Header />
        <div className={styles.main}>
          <div className={styles.imageContainer}>
            <Image
              src={currentImage || '/images/notebook1.jpg'}
              alt="Notebook"
              width={1200}
              height={800}
              style={{
                width: '100%',
                height: '80vh',
                boxShadow: '25px 25px 25px rgba(0, 0, 0, 0.25)',
                borderRadius: '16px',
              }}
              priority
            />
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
