import Head from 'next/head';
// import Image from 'next/image';
// import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

// import Board from './board';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="main">
        <div className="container">
          <div className="main__title">
            <h1>Полет фантазии</h1>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
