import Head from 'next/head';
// import Image from 'next/image';
import localFont from 'next/font/local';
// import styles from '@/styles/Home.module.css';
import Button from '@/components/Button';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Board from './Board';

const inter = localFont({
  src: [
    {
      path: './fonts/Inter-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/Inter-Regular.ttf',
      weight: '400',
    },
    {
      path: './fonts/Inter-SemiBold.ttf',
      weight: '600',
    },
  ],
  variable: '--font-inter',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="container">
        <div className={`${inter.className}`}>
          <main className="main">
            <Button
              inlineStyle={{ width: '300px' }}
              text="Войти"
              // eslint-disable-next-line no-console
              onClick={() => console.log('click')}
              type="submit"
            />
          </main>
        </div>
      </div>
      <Footer />

      <Board />
    </>
  );
}
